const questionsDatabase = [
    // ════════════════════════════════════════════════
    // CẤP 1 — Nhẹ nhàng, vui vẻ, tìm hiểu
    // ════════════════════════════════════════════════

    // --- Lắng Nghe ---
    { id: 101, type: "listen", level: 1, text: "Lần đầu tiên gặp nhau ở rạp phim, ấn tượng lớn nhất của bạn về đối phương là gì?" },
    { id: 102, type: "listen", level: 1, text: "Điều gì ở đối phương khiến bạn thấy buồn cười nhất nhưng rất đáng yêu?" },
    { id: 103, type: "listen", level: 1, text: "Đánh giá mức độ 'đẹp trai/xinh gái' của người kia hôm nay theo thang điểm 10?" },
    { id: 104, type: "listen", level: 1, text: "Nếu được miêu tả đối phương bằng một loại đồ uống, bạn sẽ chọn gì? Vì sao?" },
    { id: 105, type: "listen", level: 1, text: "Hôm nay bạn đã mỉm cười vì điều gì nhất? (Ngoài đối phương ra nhé)" },
    { id: 106, type: "listen", level: 1, text: "Tính cách nào của người đối diện mà bạn thấy giống mình nhất?" },
    { id: 107, type: "listen", level: 1, text: "Nếu 2 đứa lạc trên một hòn đảo, bạn nghĩ ai sẽ là người sinh tồn tốt hơn?" },
    { id: 108, type: "listen", level: 1, text: "Điều gì ở đối diện khiến bạn tò mò nhất lúc mới quen nhưng chưa dám hỏi?" },
    { id: 109, type: "listen", level: 1, text: "Góc mặt nào của đối phương mà bạn thấy 'cuốn' nhất?" },
    { id: 110, type: "listen", level: 1, text: "Bạn là người thích lên kế hoạch trước hay thích bất ngờ, ngẫu hứng hơn?" },
    { id: 111, type: "listen", level: 1, text: "Nếu có siêu năng lực, bạn sẽ chọn đọc suy nghĩ hay du hành thời gian?" },
    { id: 112, type: "listen", level: 1, text: "Món ăn mà bạn có thể ăn suốt đời không chán là gì?" },
    { id: 113, type: "listen", level: 1, text: "Bạn thuộc kiểu người ban đêm hay ban ngày? Sáng dậy sớm vui hay thức khuya sướng hơn?" },
    { id: 114, type: "listen", level: 1, text: "Bài hát nào mà mỗi khi nghe bạn đều nghĩ về một kỷ niệm cụ thể?" },
    { id: 115, type: "listen", level: 1, text: "Nếu được quay về 1 ngày bất kỳ trong quá khứ để sống lại, bạn chọn ngày nào?" },
    { id: 116, type: "listen", level: 1, text: "Bạn thích đi biển hay đi núi hơn? Vì sao?" },
    { id: 117, type: "listen", level: 1, text: "Khi bị stress, bạn thường làm gì để xả hơi?" },
    { id: 118, type: "listen", level: 1, text: "Bộ phim/bộ truyện nào đã ảnh hưởng đến cách bạn nhìn cuộc sống?" },
    { id: 119, type: "listen", level: 1, text: "Thử miêu tả tính cách của mình bằng 3 từ. Xem người kia có đồng ý không!" },
    { id: 120, type: "listen", level: 1, text: "Bạn là người sến hay cool? Tự đánh giá thử xem?" },
    { id: 121, type: "listen", level: 1, text: "Sở thích 'bí mật' mà bạn ít khi kể cho ai nghe là gì?" },
    { id: 122, type: "listen", level: 1, text: "Nếu có 1 ngày được làm bất kỳ nghề nào khác, bạn sẽ chọn nghề gì?" },
    { id: 123, type: "listen", level: 1, text: "Bạn thích nấu ăn hay thích được nấu cho ăn hơn? Món sở trường là gì?" },
    { id: 124, type: "listen", level: 1, text: "Một buổi hẹn lý tưởng trong đầu bạn trông như thế nào?" },
    { id: 125, type: "listen", level: 1, text: "Bạn có thói quen đặc biệt nào trước khi ngủ không?" },
    { id: 126, type: "listen", level: 1, text: "Loại thời tiết nào khiến bạn cảm thấy hạnh phúc nhất?" },
    { id: 127, type: "listen", level: 1, text: "Bạn thích xem phim ở rạp hơn hay cuộn chăn xem ở nhà hơn?" },
    { id: 128, type: "listen", level: 1, text: "Nếu trúng số 10 tỷ, điều đầu tiên bạn làm là gì?" },
    { id: 129, type: "listen", level: 1, text: "Bạn có nuôi thú cưng không? Nếu được chọn, bạn thích nuôi con gì nhất?" },
    { id: 130, type: "listen", level: 1, text: "Kỹ năng nào bạn luôn muốn học nhưng chưa bao giờ bắt đầu?" },
    { id: 131, type: "listen", level: 1, text: "Bạn thường dành thời gian rảnh làm gì nhiều nhất?" },
    { id: 132, type: "listen", level: 1, text: "Nếu phải sống ở một quốc gia khác, bạn sẽ chọn đâu?" },
    { id: 133, type: "listen", level: 1, text: "Bạn có hay nói mơ không? Giấc mơ gần nhất mà bạn nhớ là gì?" },

    // --- Hành Động ---
    { id: 151, type: "action", level: 1, text: "Nhìn thẳng vào mắt người đối diện trong 10 giây mà không chớp mắt. Ai chớp mắt trước sẽ bị búng trán nhẹ." },
    { id: 152, type: "action", level: 1, text: "Nắm tay người kia và đan các ngón tay vào nhau, giữ nguyên trong suốt 2 lượt chơi tiếp theo." },
    { id: 153, type: "action", level: 1, text: "Hãy thử đoán tay ai đang lạnh hơn bằng cách chạm nhẹ mu bàn tay nhau." },
    { id: 154, type: "action", level: 1, text: "Cùng nghe chung một nửa bài hát mà bạn đang thích (mỗi người 1 bên tai nghe)." },
    { id: 155, type: "action", level: 1, text: "Nhắm mắt lại và để đối phương vuốt tóc bạn 1 cái thật nhẹ nhàng." },
    { id: 156, type: "action", level: 1, text: "Thi xem ai có thể làm mặt 'giận dỗi' đáng yêu hơn. Người kia làm trọng tài." },
    { id: 157, type: "action", level: 1, text: "Để hai đầu ngón tay trỏ chạm nhau giống như E.T trong 5 giây." },
    { id: 158, type: "action", level: 1, text: "Giả vờ như hai người vừa mới quen ngày hôm nay. Mở lời làm quen lại bằng một câu sến nhất có thể." },
    { id: 159, type: "action", level: 1, text: "Chụp 1 tấm ảnh selfie của cả hai ngay lúc này (để mai mốt còn nhớ lại)." },
    { id: 160, type: "action", level: 1, text: "Vẽ một trái tim vô hình lên không trung và 'thổi' nó về phía đối phương." },
    { id: 161, type: "action", level: 1, text: "Bắt chước giọng nói hoặc cách nói chuyện đặc trưng của đối phương trong 30 giây." },
    { id: 162, type: "action", level: 1, text: "Dùng 30 giây để kể về ngày hôm nay của bạn, nhưng phải kể theo phong cách MC dẫn chương trình." },
    { id: 163, type: "action", level: 1, text: "Hát một đoạn bài hát mà bạn nghĩ sẽ khiến người kia bất ngờ nhất." },
    { id: 164, type: "action", level: 1, text: "Gửi 1 emoji trên điện thoại cho người kia mà không nói gì. Người kia phải đoán ý nghĩa." },
    { id: 165, type: "action", level: 1, text: "Thi oẳn tù tì, ai thua phải nói 'Tôi thích nụ cười của bạn' bằng giọng robot." },
    { id: 166, type: "action", level: 1, text: "Quay một video 10 giây nói lời chúc ngày mới vui vẻ cho đối phương, thật tình cảm." },
    { id: 167, type: "action", level: 1, text: "Hai người cùng nhau tạo 1 kiểu bắt tay bí mật chỉ riêng mình biết." },
    { id: 168, type: "action", level: 1, text: "Nói 1 câu tán tỉnh 'cliché' nhất mà bạn biết, bằng giọng thật nghiêm túc." },
    { id: 169, type: "action", level: 1, text: "Mở YouTube, tìm 1 bài hát miêu tả đúng cảm xúc của bạn lúc này và mở cho người kia nghe." },
    { id: 170, type: "action", level: 1, text: "Nhắn tin cho 1 người bạn thân: 'Tui đang có date nè!' rồi chụp màn hình phản ứng cho đối phương xem." },

    // ════════════════════════════════════════════════
    // CẤP 2 — Sâu lắng, chăm sóc, tính cách
    // ════════════════════════════════════════════════

    // --- Lắng Nghe ---
    { id: 201, type: "listen", level: 2, text: "Lần deep talk ở Phố Cổ, câu nói nào của đối phương khiến bạn suy nghĩ nhiều nhất khi về nhà?" },
    { id: 202, type: "listen", level: 2, text: "Gần đây bạn có điều gì mệt mỏi trong công việc/học tập chưa nói ra không?" },
    { id: 203, type: "listen", level: 2, text: "Khoảnh khắc nào bạn thực sự cảm thấy người đối diện mang lại cảm giác an toàn?" },
    { id: 204, type: "listen", level: 2, text: "Trước đây, điều gì từng làm bạn lo sợ nhất khi bắt đầu một mối quan hệ?" },
    { id: 205, type: "listen", level: 2, text: "Khi bạn buồn, đối phương nên im lặng ở bên cạnh hay nói những lời an ủi?" },
    { id: 206, type: "listen", level: 2, text: "Nếu xảy ra cãi vã lớn, bạn mong muốn chúng ta sẽ giải quyết thế nào?" },
    { id: 207, type: "listen", level: 2, text: "Hành động nhỏ nhặt (không phải quà vật chất) nào từng khiến bạn bị chạm tới tim nhất?" },
    { id: 208, type: "listen", level: 2, text: "Bí mật ngớ ngẩn nhất hồi bé của bạn là gì mà giờ vẫn còn nhớ?" },
    { id: 209, type: "listen", level: 2, text: "Bạn thuộc kiểu người giữ cảm xúc trong lòng hay nói ra hết? Điều đó ảnh hưởng bạn thế nào?" },
    { id: 210, type: "listen", level: 2, text: "Bạn có tính cách gì mà mình muốn thay đổi nhưng chưa bao giờ thay đổi được?" },
    { id: 211, type: "listen", level: 2, text: "Nếu phải chọn: được yêu nhiều hơn hay yêu người khác nhiều hơn, bạn chọn cái nào?" },
    { id: 212, type: "listen", level: 2, text: "Giấc mơ lớn nhất của bạn (về sự nghiệp, cuộc sống) 5 năm nữa là gì?" },
    { id: 213, type: "listen", level: 2, text: "Bạn đối xử với bạn bè thân như thế nào? Có khác gì so với cách đối xử với người yêu không?" },
    { id: 214, type: "listen", level: 2, text: "Ai trong gia đình bạn ảnh hưởng đến tính cách của bạn nhiều nhất? Vì sao?" },
    { id: 215, type: "listen", level: 2, text: "Bạn có tin vào linh cảm/phong thủy/tâm linh không? Đến mức nào?" },
    { id: 216, type: "listen", level: 2, text: "Bạn cảm thấy thế nào khi một người thể hiện sự quan tâm quá mức? Áp lực hay trân trọng?" },
    { id: 217, type: "listen", level: 2, text: "Một ngày nghỉ lý tưởng của bạn trông như thế nào? Mô tả chi tiết từ sáng đến tối." },
    { id: 218, type: "listen", level: 2, text: "Bạn có bao giờ giả vờ mạnh mẽ trong khi thực ra rất mệt không? Lúc đó bạn cần gì?" },
    { id: 219, type: "listen", level: 2, text: "Bạn nghĩ thế nào là 'trưởng thành' thực sự? Mình đã trưởng thành chưa?" },
    { id: 220, type: "listen", level: 2, text: "Nếu phải sống 1 tháng không có điện thoại, bạn sẽ thấy thế nào?" },
    { id: 221, type: "listen", level: 2, text: "Công việc hằng ngày của bạn có phần nào mà bạn thực sự enjoy không? Đó là phần gì?" },
    { id: 222, type: "listen", level: 2, text: "Bạn có thói quen xấu nào mà bản thân biết rõ nhưng vẫn không bỏ được?" },
    { id: 223, type: "listen", level: 2, text: "Bạn thường xử lý thế nào khi bị hiểu lầm? Giải thích ngay hay đợi nguội rồi nói?" },
    { id: 224, type: "listen", level: 2, text: "Trong công việc/học tập, bạn là kiểu người làm xong sớm rồi chơi hay để sát deadline mới làm?" },
    { id: 225, type: "listen", level: 2, text: "Bạn có sợ sự cô đơn không? Hay bạn thực ra thích có thời gian một mình?" },
    { id: 226, type: "listen", level: 2, text: "Điều gì khiến bạn mất hứng nhanh nhất khi nói chuyện với ai đó?" },
    { id: 227, type: "listen", level: 2, text: "Bạn là kiểu người dễ tha thứ hay sẽ nhớ rất lâu khi bị tổn thương?" },
    { id: 228, type: "listen", level: 2, text: "Nếu đồng nghiệp/bạn học nói xấu bạn sau lưng, bạn sẽ xử lý thế nào?" },
    { id: 229, type: "listen", level: 2, text: "Bạn thường đánh giá một người qua điều gì đầu tiên? Ngoại hình, giọng nói, hay hành động?" },
    { id: 230, type: "listen", level: 2, text: "Có khoảnh khắc nào trong tuần này mà bạn cảm thấy rất vui nhưng chưa kể cho ai?" },
    { id: 231, type: "listen", level: 2, text: "Bạn nghĩ mình giỏi lắng nghe người khác không? Tự chấm điểm đi." },
    { id: 232, type: "listen", level: 2, text: "Điều gì ở công việc/học tập hiện tại khiến bạn cảm thấy áp lực nhất?" },
    { id: 233, type: "listen", level: 2, text: "Bạn có hay so sánh mình với người khác không? Khi nào thì bạn hay làm vậy nhất?" },

    // --- Hành Động ---
    { id: 251, type: "action", level: 2, text: "Đưa tay cho người kia xem tay ai ấm hơn. Nếu tay đối phương lạnh, hãy tìm cách làm ấm nó ngay." },
    { id: 252, type: "action", level: 2, text: "Nhắm mắt lại 10 giây. Người kia dùng ngón tay viết 1 chữ cái lên lòng bàn tay. Đoán xem là chữ gì." },
    { id: 253, type: "action", level: 2, text: "Dựa đầu vào vai người kia trong 1 phút. Nhắm mắt lại và chỉ im lặng cảm nhận." },
    { id: 254, type: "action", level: 2, text: "Nắm chặt cả 2 tay người kia, nhìn thẳng vào mắt và nói: 'Cảm ơn vì đã ở đây'." },
    { id: 255, type: "action", level: 2, text: "Đọc tin nhắn đầu tiên bạn gửi cho người kia (nếu còn giữ) hoặc tin nhắn dễ thương nhất." },
    { id: 256, type: "action", level: 2, text: "Xoa nhẹ lên thái dương của đối phương nếu họ trông đang mệt mỏi." },
    { id: 257, type: "action", level: 2, text: "Dùng giọng điệu trẻ con để kể lại 1 chuyện xui xẻo gần đây, người kia phải lắng nghe và 'dỗ'." },
    { id: 258, type: "action", level: 2, text: "Đặt nhẹ bàn tay lên ngực trái (tim) của người đối diện để cảm nhận nhịp đập trong 15 giây." },
    { id: 259, type: "action", level: 2, text: "Vuốt ve sống lưng của đối phương chậm rãi, nhẹ nhàng trong 30 giây." },
    { id: 260, type: "action", level: 2, text: "Để người kia tạo 1 dáng chụp ảnh 'kỳ dị' cho bạn. Phải giữ nguyên 5 giây để chụp." },
    { id: 261, type: "action", level: 2, text: "Mở Zalo/Messenger, gửi 1 sticker cute nhất có thể cho người ngồi đối diện ngay lúc này." },
    { id: 262, type: "action", level: 2, text: "Giả vờ bạn là phóng viên. Phỏng vấn đối phương: 'Bạn nghĩ gì về người ngồi cạnh bạn?' Trả lời nghiêm túc." },
    { id: 263, type: "action", level: 2, text: "Viết trên ghi chú điện thoại 1 điều bạn chưa bao giờ nói trực tiếp, rồi đưa cho người kia đọc." },
    { id: 264, type: "action", level: 2, text: "Hãy khen đối phương 3 điều cụ thể (không được nói 'xinh' hoặc 'đẹp trai' chung chung)." },
    { id: 265, type: "action", level: 2, text: "Cùng nhau đặt 1 nickname mới cho đối phương mà chỉ 2 người biết." },
    { id: 266, type: "action", level: 2, text: "Gọi 1 cuộc điện thoại cho người kia (dù đang ngồi cạnh), nói 1 câu ngọt rồi cúp máy." },
    { id: 267, type: "action", level: 2, text: "Mở gallery điện thoại, cho người kia xem 3 tấm ảnh bất kỳ (random lướt). Kể câu chuyện sau mỗi ảnh." },
    { id: 268, type: "action", level: 2, text: "Hai người cùng nhắm mắt, đếm đến 3, rồi nói to 1 từ bất kỳ. Nếu trùng → trời định!" },
    { id: 269, type: "action", level: 2, text: "Kể 1 kỷ niệm đáng xấu hổ của bạn bằng giọng tự hào nhất có thể." },
    { id: 270, type: "action", level: 2, text: "Đứng dậy và diễn lại khoảnh khắc đầu tiên gặp nhau theo phong cách phim Hàn." },

    // ════════════════════════════════════════════════
    // CẤP 3 — Thân mật, chân thành, gắn kết
    // ════════════════════════════════════════════════

    // --- Lắng Nghe ---
    { id: 301, type: "listen", level: 3, text: "Hôm đi bãi đá, cảm giác lúc được chăm sóc (bóp vai/chú ý) cụ thể như thế nào?" },
    { id: 302, type: "listen", level: 3, text: "Nếu ngay lúc này có một điều ước cho chúng ta, bạn sẽ ước điều gì?" },
    { id: 303, type: "listen", level: 3, text: "Người kia có 1 đặc điểm nhỏ nào (nốt ruồi, thói quen vuốt tóc...) khiến bạn cứ để ý mãi?" },
    { id: 304, type: "listen", level: 3, text: "Bạn từng cố tình giấu cảm xúc thật liên quan đến đối phương vì sợ bị đánh giá?" },
    { id: 305, type: "listen", level: 3, text: "Miêu tả mùi hương của người đối diện theo cảm nhận lúc này?" },
    { id: 306, type: "listen", level: 3, text: "Khi ở bên cạnh đối phương, phần nào trong con người bạn cảm thấy được 'sống thật' nhất?" },
    { id: 307, type: "listen", level: 3, text: "Nếu chỉ dùng 1 từ để miêu tả nụ cười của người kia, bạn chọn từ gì?" },
    { id: 308, type: "listen", level: 3, text: "Hãy tưởng tượng 5 năm nữa. Nếu chúng ta vẫn ở cạnh nhau, lúc đó tụi mình đang như thế nào?" },
    { id: 309, type: "listen", level: 3, text: "Bạn sợ mất đi điều gì nhất ở thời điểm hiện tại?" },
    { id: 310, type: "listen", level: 3, text: "Có hành động/cử chỉ nào xa hơn mà bạn tò mò muốn thử cùng nhau nhưng chưa nói ra?" },
    { id: 311, type: "listen", level: 3, text: "Bạn nghĩ tình yêu là cảm xúc nhất thời hay là sự lựa chọn mỗi ngày?" },
    { id: 312, type: "listen", level: 3, text: "Điều gì bạn ngưỡng mộ nhất ở người kia mà chưa nói trực tiếp bao giờ?" },
    { id: 313, type: "listen", level: 3, text: "Trong tất cả các lần gặp nhau, khoảnh khắc nào bạn muốn 'đóng khung' lại mãi mãi?" },
    { id: 314, type: "listen", level: 3, text: "Bạn có nghĩ mình là người dễ tổn thương không? Người kia có thể làm gì để chữa lành?" },
    { id: 315, type: "listen", level: 3, text: "Nếu mai mốt có ai hỏi 'vì sao chọn người đó?', bạn sẽ trả lời thế nào?" },
    { id: 316, type: "listen", level: 3, text: "Bạn tin rằng hai người có thể dạy cho nhau điều gì lớn nhất?" },
    { id: 317, type: "listen", level: 3, text: "Ngôn ngữ tình yêu chính của bạn là gì? (Lời nói, hành động, quà tặng, thời gian, tiếp xúc)" },
    { id: 318, type: "listen", level: 3, text: "Bạn đã bao giờ cảm thấy 'sai thời điểm đúng người' chưa? Bây giờ thì sao?" },
    { id: 319, type: "listen", level: 3, text: "Có phiên bản nào của bạn mà bạn không muốn ai thấy? Nếu đối phương vô tình thấy thì sao?" },
    { id: 320, type: "listen", level: 3, text: "Bạn đã từng phải hy sinh điều gì quan trọng vì một ai đó? Bạn có hối hận không?" },
    { id: 321, type: "listen", level: 3, text: "Nếu chúng ta có 1 cuốn sổ chung ghi lại mọi thứ, điều đầu tiên bạn muốn viết vào là gì?" },
    { id: 322, type: "listen", level: 3, text: "Bạn có hay nhớ về một ai đó lúc nửa đêm không? Khi nào thì điều đó xảy ra nhiều nhất?" },
    { id: 323, type: "listen", level: 3, text: "Điều gì khiến bạn cảm thấy được trân trọng nhất trong một mối quan hệ?" },
    { id: 324, type: "listen", level: 3, text: "Bạn sẵn sàng đánh đổi điều gì để mối quan hệ này bền lâu?" },

    // --- Hành Động ---
    { id: 351, type: "action", level: 3, text: "Người kia đang rất mệt mỏi. Hãy giúp massage vai và cổ trong vòng 1 phút để thư giãn." },
    { id: 352, type: "action", level: 3, text: "Hãy ôm người kia một cái thật chặt, ít nhất 10 giây, giống như lần ở Phố Cổ nhưng ấm áp hơn." },
    { id: 353, type: "action", level: 3, text: "Vuốt nhẹ từ má xuống cằm của đối phương và giữ ánh mắt trong 10 giây." },
    { id: 354, type: "action", level: 3, text: "Hôn nhẹ lên trán đối phương." },
    { id: 355, type: "action", level: 3, text: "Thì thầm vào tai người đối diện một câu ngọt ngào nhất mà bạn nghĩ ra ngay lúc này." },
    { id: 356, type: "action", level: 3, text: "Nhích lại sát người kia đến mức vai chạm vai, và giữ vị trí đó đến hết ván chơi." },
    { id: 357, type: "action", level: 3, text: "Dùng ngón tay vuốt từ từ dọc mu bàn tay người kia, thật chậm." },
    { id: 358, type: "action", level: 3, text: "Nắm mặt người đối diện bằng 2 tay (nâng má), và nói 'Mong sẽ luôn thấy nụ cười này'." },
    { id: 359, type: "action", level: 3, text: "Ôm trọn đối phương từ phía trước, để cằm lên vai họ trong 15 giây." },
    { id: 360, type: "action", level: 3, text: "Viết lên lòng bàn tay người kia 3 chữ cái bí mật. Họ phải đoán. (Gợi ý: I, L, U)" },
    { id: 361, type: "action", level: 3, text: "Nghiêng đầu dựa vào nhau, nhắm mắt, cùng hít 3 hơi thở sâu thật chậm." },
    { id: 362, type: "action", level: 3, text: "Cầm tay đối phương, đưa lên gần môi, hôn nhẹ lên mu bàn tay." },
    { id: 363, type: "action", level: 3, text: "Nhìn đối phương 20 giây. Không nói gì. Chỉ nhìn. (Thử thách câm lặng đầy cảm xúc)" },
    { id: 364, type: "action", level: 3, text: "Nói cho đối phương 1 điều mà bạn chưa dám nói trực tiếp (bằng giọng thật nhỏ)." },
    { id: 365, type: "action", level: 3, text: "Lấy điện thoại, quay 1 video ngắn nói 'Lời hứa hẹn cho ngày mai' dành riêng cho người kia." },
    { id: 366, type: "action", level: 3, text: "Kéo người kia vào và ôm từ phía sau (back hug) trong 20 giây." },
    { id: 367, type: "action", level: 3, text: "Đặt tay lên vai đối phương, bóp nhẹ nhàng và nói: 'Bạn vất vả rồi, nghỉ ngơi đi'." },
    { id: 368, type: "action", level: 3, text: "Cùng nhau nhắm mắt lại 10 giây. Khi mở mắt, nói thứ đầu tiên hiện trong đầu về người kia." },

    // ═══ LÁ BÀI ĐẶC QUYỀN — Surprise ═══
    { 
        id: 999, 
        type: "surprise", 
        level: 3, 
        text: "🎁 LÁ BÀI ĐẶC QUYỀN: Bạn được quyền yêu cầu đối phương nhắm mắt lại 10 giây. Sau đó, hãy tặng cho họ một điều mà bạn đã ấp ủ từ lâu. Đối phương KHÔNG ĐƯỢC từ chối! ❤️"
    }
];

// Tin nhắn Notification ngẫu nhiên
const notificationsLove = [
    "Chỉ có gặp anh là hứng thú thôi á ~ 🙈",
    "Ngại gì chứ, lại đây anh ôm 🤗",
    "Trời Ninh Bình hôm nay đẹp thật, nhưng sao đẹp bằng... 🥰",
    "M&K — Khoảng cách bằng 0 💑",
    "Minh ơi, đừng ngại nhé! Khoa đang nhìn em bằng ánh mắt nồng cháy kia kìa 🔥",
    "Giáo viên tương lai ơi, thả lỏng xíu nào~ 🌸",
    "Nam châm ngược dấu thì hút nhau đó 🧲",
    "Khoa này, điểm 10 cho sự tinh tế nha 💯",
    "Trời lạnh thế này tay ai đang ấm hơn nhỉ? ❄️",
    "Có ai đó vừa đỏ mặt kìa 😳",
    "Thời gian ngừng nhen~ ⏱️",
    "Daaaa... em ngại quá á~ 🫣",
    "Hai đứa cute phết đó nha 💕",
    "Ai đang nhìn trộm ai kìa... 👀",
];
